### PR TITLE
fix: Refactor generate cli

### PR DESCRIPTION
**Pull request by wtrocki**
# Motivation

Use the latest and greatest Graphback (still RC as we trying to announce it as beta and still finding some simple issues when testing), but it is a much more advanced version that it is currently integrated with cli. 

We have added plugins capability which changes the way we do things etc.
I also made multiple improvements to server and client templates. 
More work to come.

### CODE REVIEW

**Comment by wtrocki** [comment]
Not sure why common package is not there

**Comment by wtrocki** [comment]
@craicoverflow Our CLI is locked to the `15.0.0-rc.2` and it causes all sorts of issues with user integrations.

What I'm thinking we should do is to allow any graphql version then yarn will be able to find common one and this will hopefully work.

Our CLI is designed to work with both standalone and embedded into project.
When embedded it will cause issues around graphql package and require to use the exact package. Moving entire CLI to rc2 is quite risky so we can:

- Downgrade to latest release
- Use some wildcard that will allow yarn to figure out one version

**Comment by wtrocki** [comment]
@ardatan WDYT to have only fullstack template and do not include backend for init operation. Backend and full-stack are mostly the same, but they introduce additional maintenance costs. We have done tons of improvements to full-stack template including new refined client-side implementation.

This also introduces a problem with testing (we were always focusing on testing fullstack app and never picked backend one).
While it is no problem to get backend done for this. I'm thinking more for long run/maintenance and simplicity of the init.

**Comment by craicoverflow** [comment]
> @craicoverflow Our CLI is locked to the `15.0.0-rc.2` and it causes all sorts of issues with user integrations.
> 
> What I'm thinking we should do is to allow any graphql version then yarn will be able to find common one and this will hopefully work.
> 
> Our CLI is designed to work with both standalone and embedded into project.
> When embedded it will cause issues around graphql package and require to use the exact package. Moving entire CLI to rc2 is quite risky so we can:
> 
>     * Downgrade to latest release
> 
>     * Use some wildcard that will allow yarn to figure out one version

I prefer downgrading to latest stable release. If the RC version is causing problems and we don't **need** it for anything blocking then there is no rush on it.

**Pull request merged**
