### PR TITLE
Re-addition of react-fullstack-advanced to create boilerplate

### PR DESCRIPTION
**Pull request by bhayward93**
react-fullstack-advanced was missing from the create boilerplate options. I've simply re-added it.

### CODE REVIEW

**Comment by bhayward93** [comment]
@mitchlanglois I tried to get it to download eventually and it didn't work for me; the directory structure was flattened, but the files looked to have been generated. Running in on Manjaro though so wasn't sure if it was environmental.

**Comment by mitchlanglois** [comment]
@bhayward93 Interesting... I'll give it a try and I'll let you know if it works.

**Comment by austincondiff** [comment]
Any update on this issue?

**Comment by bhayward93** [comment]
Not that I have heard, unfortunately.

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0` Checkout new instructions and we will be happy to hear your feedback. Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
We have just released a new structure for GraphQL CLI in new alpha versions `4.0.0-alpha.XXX`.

We suggest to use the `init` command of GraphQL CLI which was completely rewritten! 
Checkout the [new instructions](https://github.com/urigo/graphql-cli#usage--initialization) and the [migration guide](https://github.com/urigo/graphql-cli#migration-from-3xx-to-4xx) on the docs and let us know your feedback. 

Feel free to contact us by opening an issue or using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9

**Pull request closed without merging**
