### PR TITLE
Providing a ci option to avoid printing the timestamp for example in ci

### LINKED ISSUE #458: Is it possible to avoid printing the timestamp when running get-schema for example in ci?
Is there a way to avoid printing the timestamp in the generated schema?
Happy to provide a pr if you think this it can be useful

### PR DESCRIPTION
**Pull request by dbertella**
This will eventually close #458 
I didn't test it myself, I just want to know your opinion in case, and if it's useful I can work on it.

### CODE REVIEW

**Comment by jakubknejzlik** [comment]
@dbertella makes sense to me, although I would consider:
1) renaming the flag to something more related to the update (`ci` seems to be a little bit to broad, maybe `--timestamp` with default value to true?)
2) updating commit messages :) (just detail)

**Comment by dbertella** [comment]
Sounds good, I will follow it up with a better pr if you feel like it can be useful, also not sure about the source, it might be under a flag too, sometimes I generate my schema from test environment just because prod is not ready at the time of pr, it might be good to skip this info as well to have a cleaner file.

**Comment by jakubknejzlik** [comment]
As I'm currently trying to create some automation process and we are putting all the stuff in git repository which triggers CI pipelines, it would be really handy to push stuff only if there are any changes in schema (which I think may be also your use case :) ). Although it would be great to get some feedback from author or other contributors about this.
As for the source it makes sense too (currently we have feature/release deployments and we are getting the schema from local deployment in CI - having the schema without http://localhost:xxxx would be nice)

**Comment by dbertella** [comment]
Should be better now, added two variables, timestamp and source, and fix the commit message.
Let me know what you think

**Comment by dbertella** [comment]
Hey guys any thought on this one? It's very annoying to have timestamp conflict when different people work on the same autogenerated schema

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0` Checkout new instructions and we will be happy to hear your feedback. Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
We've just released a new version and an alpha release channel for GraphQL CLI - `4.0.0-alpha.XXX`!

We've changed the `get-schema` command to use [GraphQL Code Generator](http://graphql-code-generator.com) plugin of GraphQL CLI with the Codegen's [`schema-ast` plugin](https://graphql-code-generator.com/docs/plugins/schema-ast). 

Could you check it out and see if providing that option is still beneficial?
Is so, we would love to help you migrate this PR to the new codebase!

Checkout new instructions and the [migration guide](https://github.com/urigo/graphql-cli#migration-from-3xx-to-4xx) and we will be happy to hear your feedback during the alpha period!

Feel free to contact us by opening an issue or using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9

**Pull request closed without merging**
