### PR TITLE
fix: release 4.1.0-beta.1

### PR DESCRIPTION
**Pull request by wtrocki**
Trying to launch new beta after migration to graphback 0.15.0

### CODE REVIEW

**Comment by wtrocki** [comment]
Having issues with the release 

`
 yarn release:next
`

```
npm ERR! 404
  '@graphql-cli/init@4.1.0-beta.1' is not in the npm registry.
```

Possible npm issues.

**Comment by wtrocki** [comment]
Looks like scripts need to be updated. Seems like plugins were pulled out of the cli. 
Since we using Yargs we might do the same (we actually have init and generate and serve commands already - which means that cli will become really lightweight. 

@machi1990 @craicoverflow WDYT?

**Comment by craicoverflow** [comment]
There is no init command in Graphback, but generate and serve commands can be used

**Comment by wtrocki** [comment]
I will configure auto releases in the mean time we can use plain generate here to simplify workflows. Next we need to invest into init more. GraphQL cli need more love

**Comment by wtrocki** [comment]
Ok.. I see this being updated. We going to add new release and create another one

**Pull request closed without merging**
