### PR TITLE
fix: access introspection data in get-schema

### PR DESCRIPTION
**Pull request by lennyburdette**
`GraphQLEndpoint.resolveIntrospection()` returns a full graphql response, so we have to pluck the `data` property off before passing it to `buildClientSchema` (which will then access the `__schema` property.)

To reproduce the error:
```sh
$ npm -g install graphql-cli@2.16.7
$ graphql get-schema -j -o full-schema.json -e http://localhost:4000/graphql
⚠ Cannot read property 'types' of undefined
```

As more proof that this is correct, `GraphQLEndpoint.resolveSchema` actually does the same thing: https://github.com/prisma/graphql-config/blob/master/src/extensions/endpoints/EndpointsExtension.ts#L145

### CODE REVIEW

**Comment by nartc** [comment]
So so need this to be merged

**Comment by azdanov** [comment]
Have the same issue when trying to get a JSON schema from a Gatsby project.

**Comment by xzyfer** [comment]
Please progress this

**Comment by lennyburdette** [comment]
To whoever is watching over this project: I was able to pass CI by changing the pkg config to use node 10. I'm not sure why "node9" isn't work anymore. 
```json
"pkg": {
  "scripts": "dist/**/*.js",
  "targets": [
    "node10-alpine-x64",
    "node10-linux-x64",
    "node10-macos-x64",
    "node10-win-x64"
  ]
},
```
I suspect this would technically be a breaking change, so I removed it from my branch. My change should be good to merge as is! Thank you!

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0` we suggest to use GraphQL Code Generator plugin of GraphQL CLI with Codegen's `schema-ast` plugin. Checkout new instructions and we will be happy to hear your feedback. Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
We've just released a new version and an alpha release channel for GraphQL CLI - `4.0.0-alpha.XXX`!

We've changed the `get-schema` command to use [GraphQL Code Generator](http://graphql-code-generator.com) plugin of GraphQL CLI with the Codegen's [`schema-ast` plugin](https://graphql-code-generator.com/docs/plugins/schema-ast). 

Could you check it out and see if providing that option is still beneficial with how the new codebase handles errors?
Is so, we would love to help you migrate this PR to the new codebase!

Checkout new instructions and the [migration guide](https://github.com/urigo/graphql-cli#migration-from-3xx-to-4xx) and we will be happy to hear your feedback during the alpha period!

Feel free to contact us by opening an issue or using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9

**Pull request closed without merging**
