### PR TITLE
Re-enable boilerplate option

### LINKED ISSUE #471: The --boilerplate option has been removed without providing an alternative
**Describe the bug**

In [this commit](https://github.com/graphql-cli/graphql-cli/commit/39d5ba421b451cd76dfb0c81b630d1dadecb0cd3) the `--boilerplate` option has been removed without providing an alternative or a clear reason why.

This breaks various scripts and documentation on various sites and books (including the one I'm writing).

I would love to see the option back. 

**To Reproduce**
1. install `graphql-cli` globally
2. Run `graphql create my-app --boilerplate typescript-minimal`
3. An error occurs: `Unknown argument: boilerplate`

**Expected behavior**

The boilerplate should be selected based on the parameter.

**Screenshots**

**Versions (please complete the following information):**
 - OS: macOS Mojave 
 - `graphql-cli`: 3.0.11

**Additional context**
I will see if I can add a PR that makes it work again.

Somehow it also seems to [disable](https://github.com/graphql-cli/graphql-cli/commit/39d5ba421b451cd76dfb0c81b630d1dadecb0cd3#diff-f41e9d04a45c83f3b6f6e630f10117feR29) the `update-notifier`.

### PR DESCRIPTION
**Pull request by beeman**
Fixes #471

### CODE REVIEW

**Comment by janaka** [comment]
Dear people with merge powers, when will this PR be merged to fix this issue. It's pretty major oversight to remove a CLI option (breaking change) on a minor version bump.

**Comment by beeman** [comment]
@schickling @nikolasburk could you please take a look at this or ask somebody with merge rights?

**Comment by beeman** [comment]
@maticzav could you maybe take a look at merging this? It reverts some regressions that sneaked in a few months back.

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0` Checkout new instructions and we will be happy to hear your feedback. Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
We have just released a new structure for GraphQL CLI in new alpha versions `4.0.0-alpha.XXX`.

We suggest to use the `init` command of GraphQL CLI which was completely rewritten! 
Checkout the [new instructions](https://github.com/urigo/graphql-cli#usage--initialization) and the [migration guide](https://github.com/urigo/graphql-cli#migration-from-3xx-to-4xx) on the docs and let us know your feedback. 

Feel free to contact us by opening an issue or using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9

**Pull request closed without merging**
